### ISSUE TITLE
Window center and width

### ISSUE THREAD

**Issue by heye0507** [radekosmulski/rsna-intracranial#2]
Issue:
window_center and window_width are hard code at 40 and 80.

Where the window_center and width should be im.WindowCenter and im.WindowWidth

I have run about 3000 samples, the window center mean is about 36 and window width is about 98 with std around 120. 

I am not sure setting a fixed window size is working in this case, since some images are very far from the pre-defined width. 

Let me know if you want me to PR.

Thanks,

**Comment by radekosmulski** [comment]
hey @heye0507!

The idea is that in the starter pack many of the choices are arbitrary. It is good to experiment with other values - that is part of the research process. The main thought behind a starter pack is to get you up and running and experimenting quickly

> I am not sure setting a fixed window size is working in this case, since some images are very far from the pre-defined width.

Maybe you are right :slightly_smiling_face: Based on my research into the windows, I am not sure there is an obvious answer here to be honest. Will be interesting to see what teams that perform well will do - I am guessing we'll see varied ways to tackle this.

Thx again for the heads up on this - I don't think a PR would be helpful at this point.
